package models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import lombok.Data;

import java.util.ArrayList;
import java.util.Date;

@Data
@DynamoDBTable(tableName = "posts")
public class Post {

    @DynamoDBAutoGeneratedKey
    private String id;

   PostThread thread = new PostThread();

    private String postThreadId = getPostThreadId();



    @DynamoDBHashKey(attributeName = "user_name")
    private Users fromUser;

    private String content;

    private String title;

    private Date date;

    private Integer likes;

    public Post(Users fromUser) {
        this.fromUser = fromUser;
    }


    public Post() {
    }




    public Post(String postThreadId, Users fromUser, String content, Date date, Integer likes) {


        this.postThreadId = postThreadId;
        this.fromUser = getFromUser();
        this.content = content;
        this.date = date;
        this.likes = likes;
    }

    @DynamoDBAttribute
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }


    @DynamoDBAttribute
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)

    public String getPostThreadId() {
        return this.postThreadId;

    }

    public void setPostThread(String postThreadId) {
        this.postThreadId = postThreadId;
    }


    @DynamoDBHashKey(attributeName = "user_name")
    @DynamoDBTyped(DynamoDBMapperFieldModel.DynamoDBAttributeType.S)
    public Users getFromUser() {
        return fromUser;
    }



    public void setFromUser(Users fromUser) {
        this.fromUser = fromUser;
    }


    @DynamoDBAttribute
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }


    @DynamoDBAttribute
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }


    @DynamoDBAttribute
    public Integer getLikes() {
        return likes;
    }

    public void setLikes(Integer likes) {
        this.likes = likes;
    }

    public void reply(Post post) {
        post.postThreadId = this.postThreadId;
        //this.fromUser.getPosts().add(post);
    }

    @DynamoDBAttribute
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }
}
